/** The draft response drawer. Port of `#drawer` in `app/static/index.html`.
 *
 * Editing the textarea alone changes nothing in the archive. "Save edits" is
 * what writes the text back, so the two never drift. */
import { useEffect, useState } from "react";
import { relTime } from "../lib/format";
import type { Draft } from "../lib/types";

export interface DraftDrawerProps {
  draft: Draft | null;
  cached: boolean;
  busy: boolean;
  savedAt: string | null;      // set by "Save edits", so the meta line moves
  onClose: () => void;
  onSave: (text: string) => void;
  onView: (text: string) => void;
  onDownload: (text: string) => void;
  onCopy: (text: string) => void;
  onRegenerate: () => void;
}

export default function DraftDrawer(p: DraftDrawerProps) {
  const [text, setText] = useState("");
  const [dirty, setDirty] = useState(false);

  const refId = p.draft?.ref_id ?? null;
  useEffect(() => {
    setText(p.draft?.draft_text ?? "");
    setDirty(false);
  }, [refId, p.draft?.generated_at]);

  const stamp = p.savedAt ?? p.draft?.generated_at ?? null;
  const meta = p.draft ? (p.savedAt || p.cached ? "saved " : "generated ") + relTime(stamp) : "";

  return (
    <div className={"drawer" + (p.draft ? " show" : "")} role="dialog" aria-modal="true"
         aria-label="Draft response"
         onClick={(ev) => { if (ev.target === ev.currentTarget) p.onClose(); }}>
      <div className="panel">
        <div className="head">
          <strong>Draft response</strong>
          <span className="mut mono">{meta}</span>
          <span className="grow" />
          <button className="ghost" onClick={p.onClose} autoFocus>Close</button>
        </div>
        <div className="body">
          <p className="banner">
            <strong>DRAFT — review before filing.</strong> This tool never submits to the portal.
          </p>

          <div>
            <div className="ai-card">
              <div className="ai-head">
                <span className="mark" style={{ display: "grid", placeItems: "center" }}>✦</span>
                <span className="h" style={{ margin: 0 }}>Summary</span>
              </div>
              <div>{p.draft?.summary || "(no summary)"}</div>
              <div className="ai-foot">
                ✦ Generated by Claude{stamp ? " · " + relTime(stamp) : ""}
                <button className="regen" onClick={p.onRegenerate} disabled={p.busy}>Regenerate</button>
              </div>
            </div>
          </div>

          <div>
            <p className="h">Documents required</p>
            <div>
              {p.draft?.checklist?.length
                ? p.draft.checklist.map((c, i) => (
                    <div className="checkline" key={i}><span className="box" /><span>{c}</span></div>
                  ))
                : <div className="mut">Nothing specific demanded.</div>}
            </div>
          </div>

          <div>
            <p className="h">Draft reply (editable)</p>
            <textarea id="d-text" spellCheck={false} value={text}
                      onChange={(e) => { setText(e.target.value); setDirty(true); }} />
            <div style={{ marginTop: 10, display: "flex", gap: 8, flexWrap: "wrap" }}>
              <button className="primary accent" disabled={p.busy}
                      onClick={() => { p.onSave(text); setDirty(false); }}>Save edits</button>
              <button onClick={() => p.onView(text)}>View</button>
              <button onClick={() => p.onDownload(text)}>Save</button>
              <button onClick={() => p.onCopy(text)}>Copy draft</button>
              <button className="ghost" disabled={p.busy} onClick={p.onRegenerate}>Regenerate</button>
            </div>
            <p className="mut" style={{ margin: "8px 0 0" }} hidden={!dirty}>
              Edited — press Save edits to store it.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
